name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    name: Label by branch's name pattern
    runs-on: hako-default
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/workflows/configurations/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
